version: "3.9"
services:
  client:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    restart: on-failure
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - test-docker-react

networks:
  test-docker-react:
    driver: bridge
